### ISSUE TITLE
Unable to call from android

### ISSUE THREAD

**Issue by PriyaSindkar** [cybex-dev/twilio_voice#2]
I tried calling from android but got the following exception. It was working fine 2 weeks back. I don't know what went wrong. Is my project not building properly now?

```
E/MethodChannel#twilio_voice/messages: Failed to handle method call
    com.getkeepsafe.relinker.MissingLibraryException: libtwilio_voice_android_so.so
        at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:128)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
        at com.twilio.voice.Voice.loadLibrary(Voice.java:1233)
        at com.twilio.voice.MediaFactory.instance(MediaFactory.java:31)
        at com.twilio.voice.LocalAudioTrack.create(LocalAudioTrack.java:82)
        at com.twilio.voice.LocalAudioTrack.create(LocalAudioTrack.java:29)
        at com.twilio.voice.Voice.connect(Voice.java:573)
        at com.twilio.twilio_voice.TwilioVoicePlugin.onMethodCall(TwilioVoicePlugin.java:404)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:183)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-04-12 16:13:55.207 14779-14825/com.kasper E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Unhandled error PlatformException(error, libtwilio_voice_android_so.so, null, com.getkeepsafe.relinker.MissingLibraryException: libtwilio_voice_android_so.so
        at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:128)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
        at com.twilio.voice.Voice.loadLibrary(Voice.java:1233)
        at com.twilio.voice.MediaFactory.instance(MediaFactory.java:31)
        at com.twilio.voice.LocalAudioTrack.create(LocalAudioTrack.java:82)
        at com.twilio.voice.LocalAudioTrack.create(LocalAudioTrack.java:29)
        at com.twilio.voice.Voice.connect(Voice.java:573)
        at com.twilio.twilio_voice.TwilioVoicePlugin.onMethodCall(TwilioVoicePlugin.java:404)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:183)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by diegogarciar** [comment]
weird, I haven't submitted any update to pub.dev in the last weeks, are you using that version or directly from the repo?

**Comment by PriyaSindkar** [comment]
Hi, I am using the pub in my pubspec.yaml

**Comment by diegogarciar** [comment]
Weird, have you tried flutter clean?

**Comment by PriyaSindkar** [comment]
Yes, flutter clean did the trick. Thanks and apologies for wrongly raising the issue.
