### ISSUE TITLE
Got Error MissingPluginException

### ISSUE THREAD

**Issue by Stacey940** [cybex-dev/twilio_voice#25]
Hi,

Trying to implement this on my app but I am getting error MissingPluginException. I spend days to find the problem but was not able to resolve it. Here is the error log 

Device : Pixel 4 XL

```
====================================================================================================
I/flutter ( 2856): voip- service init
I/flutter ( 2856): voip-registtering with token 
I/flutter ( 2856): voip-calling voice-accessToken
I/flutter ( 2856): androidToken is XXXXXXXXXXXXXXXXX
E/flutter ( 2856): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method isOnCall on channel twilio_voice/messages)
E/flutter ( 2856): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 2856): <asynchronous suspension>
E/flutter ( 2856): #1      _PeopleState.checkActiveCall (package:untitled/ui/people/peopleList.dart:147:22)
E/flutter ( 2856): <asynchronous suspension>
E/flutter ( 2856): 

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel twilio_voice/events:
MissingPluginException(No implementation found for method listen on channel twilio_voice/events)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:545:9)
<asynchronous suspension>
====================================================================================================
E/flutter ( 2856): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method tokens on channel twilio_voice/messages)
E/flutter ( 2856): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 2856): <asynchronous suspension>
E/flutter ( 2856): 
E/flutter ( 2856): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method hasMicPermission on channel twilio_voice/messages)
E/flutter ( 2856): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 2856): <asynchronous suspension>
E/flutter ( 2856): #1      _PeopleState._buildRow.<anonymous closure> (package:untitled/ui/people/peopleList.dart:308:30)
E/flutter ( 2856): <asynchronous suspension>
E/flutter ( 2856): 

```

Here is my AndroidMenifest.XML

```
<!--suppress AndroidDomInspection -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.untitled">
   <application
        android:label="untitled"
        android:icon="@mipmap/ic_launcher">

        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />

            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
       <service android:name="com.twilio.twilio_voice.fcm.VoiceFirebaseMessagingService" android:stopWithTask="false">
           <intent-filter>
               <action android:name="com.google.firebase.MESSAGING_EVENT" />
           </intent-filter>
       </service>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

**Comment by alexlovar** [comment]
hello, i'm going through the same error when i run the sample on **android** emulator or real device:
```
E/flutter (20054): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method getPlatformVersion on channel flutter_twilio_voice)
E/flutter (20054): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
```

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1165], locale es-419)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.56.2)
[√] Connected device (4 available)
```

**Comment by Stacey940** [comment]
I created a new project installed the plugin again and the issue with missing plugin is resolved.

**Comment by diegogarciar** [comment]
I'm glad you solved it, I'll still take a look and verify if there's something that could be improved to prevent this. Cheers!

**Comment by alexlovar** [comment]
@Stacey940 did you create a new flutter project and then replace the folder with the sample project content? or create a new project and use the pub.dev plugin version  twilio_voice: ^0.0.9 in the yaml file? could you please be more especific? thank you

**Comment by diegog-sf** [comment]
@alexlovar have you tried `flutter clean`?

**Comment by alexlovar** [comment]
thank you @diegogarciar . flutter clean and invalidate cache and restart. works
